#!/bin/sh

# $Id$
# $URL$

# exit on errors
set -e

# set nicer prompt for tracing
PS4="$0:\$LINENO> "
set -x

aclocal -I /usr/share/gettext/m4 -I /usr/share/aclocal
libtoolize --copy --force 
autoheader
automake --add-missing --copy --foreign 
autoconf

